version: "3.8"

services:
  tomcat:
    image: tomcat:10.1
    container_name: tomcat_t3
    ports:
      - "8080:8080"
      - "8443:8443"
    restart: unless-stopped

    volumes:
      - "./server.xml:/usr/local/tomcat/conf/server.xml"
      - "./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
      - "./certs:/usr/local/tomcat/certs"
      - "../../target/calculadora.war:/usr/local/tomcat/webapps/calculadora.war"
