services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: dwes2025
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: estusdiante
      MYSQL_PASSWORD: estudiante123
    ports:
      - "3307:3307"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
