services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    expose: ["80"]
    depends_on:
      db:
        condition: service_healthy
    networks: [frontend, backend]

  db:
    image: mariadb:10.5
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks: [backend]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p\"$${MYSQL_ROOT_PASSWORD}\" --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks: [frontend, backend]

  proxy:
    image: nginx:alpine
    ports:
      - "88:80"
      - "8443:443"
      - "8080:8080"
    volumes:
      - ./services/nginx:/etc/nginx/conf.d/:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      web:
        condition: service_started
    networks: [frontend, backend]

  backup:
    image: alpine:3
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./backup.sh:/backup.sh:ro
      - ./backups:/backups:rw
    command: sh -c "apk add --no-cache mariadb-client && while true; do sh /backup.sh; sleep 10; done"
    depends_on:
      - db
    networks: [backend]

  tomcat:
    image: tomcat:9.0
    expose: ["8080"]
    volumes:
      - ./services/tomcat/webapps/sample.war:/usr/local/tomcat/webapps/sample.war
    networks: [backend]

volumes:
  dbdata:

networks:
  frontend:
  backend:
